# Generated by Django 3.2 on 2021-05-01 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='course',
        ),
        migrations.RemoveField(
            model_name='scoreboard',
            name='course',
        ),
        migrations.RemoveField(
            model_name='scoreboard',
            name='user',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='ScoreBoard',
        ),
    ]
